# Generated by Django 4.2.13 on 2024-05-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Krankenhaus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("kooperationspartner", models.BooleanField(default=False)),
                ("ausbildungsstaette_name", models.CharField(max_length=200)),
                ("ausbildungsstaette_dienstposten_start", models.DateField()),
                ("ausbildungsstaette_dienstposten_end", models.DateField()),
                ("ausbildungsstaette_dienstposten_hours", models.IntegerField()),
                (
                    "ausbildungsstaette_dienstposten_occupationalgroups",
                    models.IntegerField(),
                ),
                (
                    "ausbildungsstaette_dienstposten_associatedausbildungsbloecke",
                    models.IntegerField(),
                ),
                ("ausbildungsstaette_tags", models.IntegerField()),
                ("planbare_ausbildungsbloecke_start", models.DateField()),
                ("ausbildungsstellen_start", models.DateField()),
                ("ausbildungsstellen_duration", models.IntegerField()),
                ("genehmigte_fachgebiete_id", models.IntegerField()),
                ("genehmigte_fachgebiete_duration", models.IntegerField()),
                ("dienstposten_start", models.DateField()),
                ("dienstposten_end", models.DateField()),
                ("hours", models.IntegerField()),
                ("occupationalgroups", models.IntegerField()),
                ("associatedausbildungsbloecke", models.IntegerField()),
            ],
        ),
    ]
