# Generated by Django 4.2.13 on 2024-05-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="krankenhaus",
            name="kooperationspartner",
            field=models.BooleanField(),
        ),
        migrations.AlterModelTable(
            name="krankenhaus",
            table="frontend_krankenhaus",
        ),
    ]
