# Generated by Django 4.2.13 on 2024-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0002_alter_krankenhaus_kooperationspartner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auswertung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singleMonthAssignments", models.IntegerField()),
                ("monthsWithoutTraining", models.IntegerField()),
                ("consecutiveMonthsWithoutTraining", models.IntegerField()),
                ("hospitalChanges", models.IntegerField()),
                ("departmentChanges", models.IntegerField()),
                ("monthsAtCooperationPartner", models.IntegerField()),
                ("violatedPreferences", models.IntegerField()),
                ("varMonthsWithoutTraining", models.IntegerField()),
                ("varViolatedPreferences", models.IntegerField()),
                ("departmentsWithoutTraining", models.IntegerField()),
                ("departmentsPerModule", models.IntegerField()),
            ],
        ),
    ]
