# Generated by Django 4.2.13 on 2024-06-03 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0003_auswertung"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Auswertung",
        ),
        migrations.DeleteModel(
            name="Krankenhaus",
        ),
    ]
